apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp
  labels:
    app: testapp
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: testapp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: testapp
    spec:
      containers:
        - name: testapp
          image: 926671442187.dkr.ecr.ap-southeast-1.amazonaws.com/testapp:670aa11f4ca789484d3da084424071371e39aab7
          imagePullPolicy: Always
          ports:
          - containerPort: 80