apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml

images:
- name: 926671442187.dkr.ecr.ap-southeast-1.amazonaws.com/testapp
  newTag: 5d2b32f68acc61145920d92df79925c9ed7d802f
